# Declare a Backstage Component for cloud-on-k8s-operator
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: connectors-python
  description: Ingestion Service hosting connectors that can be used to ingest data into Elasticsearch.
  annotations:
    github.com/project-slug: elastic/connectors-python
    buildkite.com/project-slug: elastic/connectors-python
spec:
  type: service
  lifecycle: experimental
  owner: group:ingestion-team
  system: buildkite
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: buildkite.elastic.dev/v1
kind: Pipeline
metadata:
  description: Connectors Service in Python Nightly Tests
  name: connectors-python-nightly
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/connectors-python-nightly
spec:
  pipeline_file: .buildkite/nightly.yml
  provider_settings:
    trigger_mode: none
  repository: elastic/connectors-python
  schedules:
    Daily 8_7:
      branch: '8.7'
      cronline: '@daily'
      message: Runs daily `8.7` e2e test
    Daily 8_8:
      branch: '8.8'
      cronline: '@daily'
      message: Runs daily `8.8` e2e test
    Daily main:
      branch: main
      cronline: '@daily'
      message: Runs daily `main` e2e test
  teams:
    everyone:
      access_level: READ_ONLY
    ingestion-team: {}
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: buildkite.elastic.dev/v1
kind: Pipeline
metadata:
  description: Connectors Service in Python
  name: connectors-python
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/connectors-python
spec:
  pipeline_file: .buildkite/pipeline.yml
  branch_configuration: main
  repository: elastic/connectors-python
  teams:
    everyone:
      access_level: READ_ONLY
    ingestion-team: {}
