################################################################################
###################### catalog-info for connectors ######################
# Declare a Backstage Component for connectors
# When doing changes validate them using https://backstage.elastic.dev/entity-validation
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "elastic-connectors"
  description: "Ingestion service hosting connectors that can be used to ingest data into Elasticsearch"
  annotations:
    backstage.io/source-location: "url:https://github.com/elastic/connectors/"
    github.com/project-slug: "elastic/connectors"
    github.com/team-slug: "elastic/ingestion-team"
    buildkite.com/project-slug: "elastic/connectors"
  tags:
    - "python"
    - "buildkite"
spec:
  type: "service"
  lifecycle: "production"
  owner: "group:ingestion-team"

###############################################################################
############################# buildkite pipelines #############################
# Declare our Buildkite pipelines
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json

# Declare the main pipeline that's used for PRs and commits
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "connectors"
  description: "Lints and tests Elastic connector framework and connector implementations"
  links:
    - title: "connectors Main Pipeline"
      url: "https://buildkite.com/elastic/connectors"
spec:
  type: "buildkite-pipeline"
  owner: "group:ingestion-team"
  system: "buildkite"
  implementation:
    apiVersion: "buildkite.elastic.dev/v1"
    kind: "Pipeline"
    metadata:
      name: "connectors"
      description: "Your Connector Service to ingest data into Elasticsearch"
    spec:
      branch_configuration: "main"
      pipeline_file: ".buildkite/pipeline.yml"
      repository: "elastic/connectors"
      teams:
        everyone:
          access_level: "READ_ONLY"
        ingestion-team: {}

############################# Nightly Test Suites #############################
# Declare daily/nightly tests pipeline
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "connectors-nightly"
  description: "Nightly Connector Service Tests"
  links:
    - title: "connectors Nightly Buildkite Jobs"
      url: "https://buildkite.com/elastic/connectors"
spec:
  type: "buildkite-pipeline"
  owner: "group:ingestion-team"
  system: "buildkite"
  implementation:
    apiVersion: "buildkite.elastic.dev/v1"
    kind: "Pipeline"
    metadata:
      name: "connectors-nightly"
      description: "Connectors Service Nightly Tests"
      links:
        - title: "Connector Service Nightly Pipeline"
          url: "https://buildkite.com/elastic/connectors-nightly"
    spec:
      pipeline_file: ".buildkite/nightly.py"
      provider_settings:
        trigger_mode: "none"
      repository: "elastic/connectors"
      schedules:
        Daily 8_9:
          branch: '8.9'
          cronline: '@daily'
          message: "Runs daily `8.9` e2e test"
        Daily 8_10:
          branch: '8.10'
          cronline: '@daily'
          message: "Runs daily `8.10` e2e test"
        Daily 8_11:
          branch: '8.11'
          cronline: '@daily'
          message: "Runs daily `8.11` e2e test"   
        Daily 8_12:
          branch: '8.12'
          cronline: '@daily'
          message: "Runs daily `8.12` e2e test"
        Daily main:
          branch: main
          cronline: '@daily'
          message: "Runs daily `main` e2e test"
      teams:
        everyone:
          access_level: "READ_ONLY"
        ingestion-team: {}


############################# Nightly Test Suites #############################
# Declare daily/nightly aarch64 tests pipeline
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "connectors-nightly-aarch64"
  description: "Nightly Connector Service Tests"
  links:
    - title: "connectors Nightly Buildkite Jobs"
      url: "https://buildkite.com/elastic/connectors"
spec:
  type: "buildkite-pipeline"
  owner: "group:ingestion-team"
  system: "buildkite"
  implementation:
    apiVersion: "buildkite.elastic.dev/v1"
    kind: "Pipeline"
    metadata:
      name: "connectors-nightly-aarch64"
      description: "Connectors Service Nightly Tests"
      links:
        - title: "Connector Service Nightly Pipeline"
          url: "https://buildkite.com/elastic/connectors-nightly-aarch64"
    spec:
      pipeline_file: ".buildkite/nightly_aarch64.py"
      provider_settings:
        trigger_mode: "none"
      repository: "elastic/connectors"
      schedules:
        Daily main:
          branch: main
          cronline: '@daily'
          message: "Runs daily `main` e2e aarch64 test"
      teams:
        everyone:
          access_level: "READ_ONLY"
        ingestion-team: {}

############################# Nightly Test Suites #############################
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "connectors-nightly-dockers"
  description: "Connectors Service Nightly Dockers"
  links:
    - title: "connectors Nightly Buildkite Jobs"
      url: "https://buildkite.com/elastic/connectors"
spec:
  type: "buildkite-pipeline"
  owner: "group:ingestion-team"
  system: "buildkite"
  implementation:
    apiVersion: "buildkite.elastic.dev/v1"
    kind: "Pipeline"
    metadata:
      name: "connectors-nightly-dockers"
      description: "Connectors Service Nightly Dockers"
      links:
        - title: "Connector Service Nightly Pipeline"
          url: "https://buildkite.com/elastic/connectors-nightly"
    spec:
      pipeline_file: ".buildkite/nightly_docker.yml"
      provider_settings:
        trigger_mode: "none"
      repository: "elastic/connectors"
      schedules:
        Daily 8_9:
          branch: '8.9'
          cronline: '@daily'
          message: "Runs daily `8.9` e2e aarch64 test"
        Daily 8_10:
          branch: '8.10'
          cronline: '@daily'
          message: "Runs daily `8.10` e2e aarch64 test"
        Daily 8_11:
          branch: '8.11'
          cronline: '@daily'
          message: "Runs daily `8.11` e2e aarch64 test"
        Daily 8_12:
          branch: '8.12'
          cronline: '@daily'
          message: "Runs daily `8.12` e2e aarch64 test"
        Daily main:
          branch: main
          cronline: '@daily'
          message: "Runs daily `main` docker"
      teams:
        everyone:
          access_level: "READ_ONLY"
        ingestion-team: {}
