FROM docker.elastic.co/wolfi/python:3.11-dev@sha256:90bd4e183e63592be2216ab504f76dfa194d1ac5138e4e33b4a9eb58421f4fc5
USER root
COPY . /connectors
WORKDIR /connectors
RUN make clean install
RUN .venv/bin/pip install -r requirements/ftest.txt
ENTRYPOINT []
