FROM docker.elastic.co/wolfi/python:3.11-dev@sha256:1662295f3a1e475b80427fc0d108dbfdc0c8fd38ef68b305485faedf57e2da9d
USER root
COPY . /connectors
WORKDIR /connectors
RUN make clean install
RUN .venv/bin/pip install -r requirements/ftest.txt
ENTRYPOINT []
