FROM docker.elastic.co/wolfi/python:3.11-dev@sha256:8d25b874b8427ae635c237a5746518600e4177a1c07f82811de199dee19bcf0c
USER root
COPY . /connectors
WORKDIR /connectors
RUN make clean install
RUN .venv/bin/pip install -r requirements/ftest.txt
ENTRYPOINT []
