FROM docker.elastic.co/wolfi/python:3.11-dev@sha256:3c41b22eb7784cce6dc44bc9fce637bb5d919fa532c9851cfdb672b65bfe7c33
USER root
COPY . /app
WORKDIR /app
RUN make clean install
RUN ln -s .venv/bin /app/bin
ENTRYPOINT []
