FROM docker.elastic.co/wolfi/python:3.11-dev@sha256:d19ae36e012b0e71e651b575154a98551b1e0419e6e47e4b9c938e37f5a4d0da
USER root
COPY . /app
WORKDIR /app
RUN make clean install
RUN ln -s .venv/bin /app/bin
ENTRYPOINT []
