[project]
name = "connectors-sdk"
version = "0.1.0"
authors = [
    { name = "Search Extract and Transform Team", email = "enterprise-search-ingestion-team@elastic.co" }
]
description = "SDK to facilitate development of Elastic connectors"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # Elastic License here
    "Operating System :: OS Independent",
]
requires-python = ">=3.10,<3.12"
dependencies = [
    "aiohttp>=3",
    "aiofiles==23.2.1",
    "pymongo==4.6.3",
    "tzcron==1.0.0",
    "pympler==1.0.1"
]

[project.optional-dependencies]
dev = [
    "ruff>=0.6.1",
    "pytest"
]

[project.urls]
Homepage = "https://github.com/elastic/connectors"
Issues = "https://github.com/elastic/connectors/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
dev-mode-dirs = ["src"]

[tool.hatch.build.targets.wheel]
sources = ["src"]
