#!/bin/bash
# Produces a list of changed files between two commits (works for merges and
# regular commits).
# Used in conjunction with the monorepo-diff-buildkite-plugin to determine
# which pipelines to upload/trigger based on the files changed.

[ $# -lt 1 ] && { echo "argument is missing."; exit 1; }

COMMIT=$1

echo 'Base branch:'
echo "$BUILDKITE_PULL_REQUEST_BASE_BRANCH"

if [[ -z $BUILDKITE_PULL_REQUEST_BASE_BRANCH ]]; then
  git fetch origin $BUILDKITE_PULL_REQUEST_BASE_BRANCH
  HEAD_BRANCH=$BUILDKITE_PULL_REQUEST_BASE_BRANCH
else
  HEAD_BRANCH=FETCH_HEAD~1
fi

echo 'Head branch:'
echo "$HEAD_BRANCH"

git diff --raw "$COMMIT".."$HEAD_BRANCH" | awk '{print $6; if($7) {print $7}}'
