#!/bin/bash
# Produces a list of changed files between two commits (works for merges and
# regular commits).
# Used in conjunction with the monorepo-diff-buildkite-plugin to determine
# which pipelines to upload/trigger based on the files changed.

[ $# -lt 1 ] && { echo "argument is missing."; exit 1; }

COMMIT=$1

echo 'Base branch:'
echo "$BUILDKITE_PULL_REQUEST_BASE_BRANCH"

echo 'Target:'
TARGET=${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-FETCH_HEAD~1}

echo "$TARGET"

if [ -n $BUILDKITE_PULL_REQUEST_BASE_BRANCH ]; then
  echo "Using base branch"      
  git fetch origin $BUILDKITE_PULL_REQUEST_BASE_BRANCH --depth=100
  HEAD_BRANCH=$BUILDKITE_PULL_REQUEST_BASE_BRANCH
else
  echo "Using head of current branch"      
  HEAD_BRANCH=FETCH_HEAD~1
fi

echo 'Head branch:'
echo "$HEAD_BRANCH"

git diff --raw "$COMMIT".."$TARGET" | awk '{print $6; if($7) {print $7}}'
