#!/bin/bash
# Produces a list of changed files between two commits (works for merges and
# regular commits).
# Used in conjunction with the monorepo-diff-buildkite-plugin to determine
# which pipelines to upload/trigger based on the files changed.

[ $# -lt 1 ] && { echo "argument is missing."; exit 1; }

COMMIT=$1

HEAD_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH:-FETCH_HEAD~1}

git diff --raw "$COMMIT".."$HEAD_BRANCH" | awk '{print $6; if($7) {print $7}}'
