agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: false

steps:
  - label: "🔨 MySQL"
    command:
      - ".buildkite/run_nigthly.sh mysql"
    artifact_paths:
      - "perf8-report-*/**/*"
  - label: "🔨 Network Drive"
    command:
      - ".buildkite/run_nigthly.sh network_drive"
    artifact_paths:
      - "perf8-report-*/**/*"
  - label: "🔨 Amazon S3"
    command:
      - ".buildkite/run_nigthly.sh s3"
    artifact_paths:
      - "perf8-report-*/**/*"
  - label: "🔨 Google Cloud Storage"
    command:
      - ".buildkite/run_nigthly.sh google_cloud_storage"
    artifact_paths:
      - "perf8-report-*/**/*"
  - label: "🔨 Azure Blob Storage"
    command:
      - ".buildkite/run_nigthly.sh azure_blob_storage"
    artifact_paths:
      - "perf8-report-*/**/*"
  - label: "🔨 Postgresql"
    command:
      - ".buildkite/run_nigthly.sh postgresql"
    artifact_paths:
      - "perf8-report-*/**/*"
  - label: "🔨 Oracle Database"
    command:
      - ".buildkite/run_nigthly.sh oracle"
    artifact_paths:
      - "perf8-report-*/**/*"
