agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: false

steps:
  - label: "🔨 Performance and functional test"
    command:
      - ".buildkite/run_nigthly.sh"
    artifact_paths:
      - "perf8-report-*/**/*"
