agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: true
  image: family/enterprise-search-ubuntu-2204-connectors-py

steps:
  - label: "🏗️ Docker images"
    command:
      - ".buildkite/publish_docker.sh"
