retry:
  automatic:
    - exit_status: -1  # Connection to the Agent was lost
      signal_reason: none
      limit: 2
    - exit_status: 255  # Timeout
      signal_reason: none
      limit: 2
    - signal_reason: 2  # Flaky test
      limit: 2

env:
  DOCKERFILE_FTEST_PATH: "Dockerfile.ftest.wolfi"

steps:
  - label: "🔨 [Python {{ matrix }}] MySQL"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "mysql"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Network Drive"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "network_drive"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Amazon S3"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "s3"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Google Cloud Storage"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "google_cloud_storage"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Azure Blob Storage"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "azure_blob_storage"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Postgresql"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "postgresql"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] System Directory"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "dir"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Oracle Database"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "oracle"
      DATA_SIZE: "small"
      SKIP_AARCH64: "true"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Sharepoint Server"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "sharepoint_server"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Sharepoint Online"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "sharepoint_online"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Microsoft SQL"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "mssql"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Jira"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "jira"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Confluence"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "confluence"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] ServiceNow"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "servicenow"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] MongoDB"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "mongodb"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
#   - label: "🔨 [Python {{ matrix }}] MongoDB Serverless"
#     command: ".buildkite/run_functional_test.sh"
#     env:
#       PYTHON_VERSION: "{{ matrix }}"
#       CONNECTOR: "mongodb_serverless"
#       DATA_SIZE: "small"
#     matrix:
#       - "3.10"
#       - "3.11"
#     artifact_paths:
#       - "perf8-report-*/**/*"
  - label: "🔨 [Python {{ matrix }}] GitHub"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "github"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Google Drive"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "google_drive"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Dropbox"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "dropbox"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] OneDrive"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "onedrive"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Salesforce"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "salesforce"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Zoom"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "zoom"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Box"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "box"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Notion"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "notion"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] Redis"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "redis"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
  - label: "🔨 [Python {{ matrix }}] GraphQL"
    command: ".buildkite/run_functional_test.sh"
    env:
      PYTHON_VERSION: "{{ matrix }}"
      CONNECTOR: "graphql"
      DATA_SIZE: "small"
    artifact_paths:
      - "perf8-report-*/**/*"
    matrix:
      - "3.10"
      - "3.11"
