agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: false

steps:
  - label: "🔨 End-to-end test"
    command: ".buildkite/run_nigthly.sh %N"
    parallelism: 5
    artifact_paths:
      - "perf8-report-*/**/*"
